"use strict:"
//this file is autogenerated don't modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.default={
	"test/remote/MyRemoteObject.ts": {
		"date": 1683401390257,
		"test.remote.MyRemoteObject": {}
	}
}